name    'jamesnetherton/atom_editor'
version '0.1.0'
source 'https://github.com/jamesnetherton/puppet-atom-editor'
author 'jamesnetherton'
license 'MIT'
summary 'Installs the Atom text editor'
description 'Installs the Atom text editor'
project_page 'https://github.com/jamesnetherton/puppet-atom-editor'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/apt', '>= 1.4.2'
